<?php

namespace App\Controller;

use App\Entity\Work;
use App\Form\WorkType;
use App\Form\WorkEditType;
use App\Repository\WorkRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class AdminController extends AbstractController
{

    /**
     * @Route("/admin", name="admin")
     */
    public function index(WorkRepository $repo)
    {
        $works = $repo->findAll();
        return $this->render('admin/index.html.twig', [
            'works' => $works
        ]);
    }

    /**
     * @Route("/admin/new", name="admin_create")
     * @Route("/admin/{id}/edit", name="admin_edit")
     */
    public function manage(Request $request, ObjectManager $manager, Work $work = null)
    {
        if (!$work) {
            $work = new Work();
        }

        $editMode = $work->getId() != null;

        if($editMode){
            $form = $this->createForm(WorkEditType::class, $work);
        } else {
            $form = $this->createForm(WorkType::class, $work);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if(!$editMode){
                /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
                $file = $work->getData()->getName();

                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                $work->getData()->setExtension($file->guessExtension());

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('data_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $work->getData()->setName($fileName);
            }

            $manager->persist($work);
            $manager->flush();

            if (!$editMode) {
                $this->addFlash('success', 'Work créé');
            } else {
                $this->addFlash('success', 'Work modifié');
            }

            return $this->redirectToRoute('admin');
        }

        return $this->render('admin/manage.html.twig', [
            'form' => $form->createView(),
            'editMode' => $editMode,
            'work' => $work
        ]);
    }

    /**
     * @Route("/admin/{id}/delete", name="admin_delete")
     */
    public function delete(Work $work, ObjectManager $manager, Filesystem $fileSystem)
    {
        $fileSystem->remove($this->getParameter('data_directory').'/'.$work->getData()->getName());
        $manager->remove($work);
        $manager->flush();
        $this->addFlash('success', 'Work supprimé');
        return $this->redirectToRoute('admin');
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
